'use client';

import { Bar, BarChart, CartesianGrid, XAxis, YAxis } from 'recharts';
import { BrainCircuit, Quote } from 'lucide-react';
import { ChartContainer, ChartTooltip, ChartTooltipContent } from '@/components/ui/chart';
import { demoFeatureContributions, demoScenario } from '@/data/demo-scenario';
import { MetricTile, PageFrame, SectionHeader } from './page-frame';

export function ExplainableAIPage() {
  return <PageFrame title="Explainable AI" subtitle="Understand the evidence behind CyberDrishti's forecast" badge="Demo Explanation">
    <div className="grid gap-3 sm:grid-cols-3"><MetricTile label="Current Stage" value={demoScenario.currentStage} tone="observed" /><MetricTile label="Predicted Stage" value={demoScenario.predictedStage} tone="forecast" /><MetricTile label="Forecast Probability" value={`${demoScenario.forecastConfidence}%`} tone="forecast" /></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]">
      <section className="panel p-4"><SectionHeader title="Feature Contribution" description="Illustrative contribution weights; no SHAP computation is performed" /><ChartContainer config={{ contribution: { label: 'Contribution', color: 'var(--chart-2)' } }} className="h-[330px] w-full aspect-auto"><BarChart data={demoFeatureContributions} layout="vertical" margin={{ left: 18, right: 24, top: 10, bottom: 0 }}><CartesianGrid horizontal={false} strokeDasharray="3 3" /><XAxis type="number" domain={[0, 30]} unit="%" tick={{ fontSize: 8 }} /><YAxis type="category" dataKey="feature" width={132} tick={{ fontSize: 8 }} /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="value" name="contribution" fill="var(--color-contribution)" radius={[0, 3, 3, 0]} /></BarChart></ChartContainer></section>
      <aside className="panel p-4"><div className="flex items-center gap-2"><BrainCircuit className="size-4 text-indigo-600" /><h2 className="text-[12px] font-bold">Why this forecast?</h2></div><Quote className="mt-6 size-7 text-indigo-200" /><p className="mt-2 text-[12px] leading-relaxed">Increasing destination-port diversity, repeated SYN activity and abnormal connection timing across recent network states contributed strongly to the Initial Access forecast.</p><div className="mt-5 rounded-md border bg-muted/40 p-3 text-[9px] leading-relaxed text-muted-foreground">This explanation is a frontend demonstration of intended model transparency. Values are predefined and are not generated by a trained inference or explainability engine.</div><h3 className="mt-5 text-[10px] font-bold">Evidence summary</h3><ul className="mt-2 space-y-2 text-[9px] text-muted-foreground"><li>• Port diversity is the largest positive contributor.</li><li>• SYN-rate acceleration supports the observed reconnaissance state.</li><li>• Failed connections increase confidence in the next-stage forecast.</li></ul></aside>
    </div>
  </PageFrame>;
}
