'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { BellRing, Eye, Search, ShieldAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { demoAlerts, type DemoAlert } from '@/data/demo-alerts';
import { cn } from '@/lib/utils';
import { MetricTile, PageFrame, SectionHeader } from './page-frame';

export function PredictiveAlertsPage() {
  const [alerts, setAlerts] = useState(demoAlerts);
  const [selected, setSelected] = useState<DemoAlert | null>(null);
  const [query, setQuery] = useState('');
  const [severity, setSeverity] = useState('All');
  const rows = useMemo(() => alerts.filter((a) => (severity === 'All' || a.severity === severity) && `${a.id} ${a.source} ${a.target} ${a.predicted}`.toLowerCase().includes(query.toLowerCase())), [alerts, query, severity]);
  const update = (id: string, status: DemoAlert['status']) => { setAlerts((items) => items.map((a) => a.id === id ? { ...a, status } : a)); setSelected((a) => a?.id === id ? { ...a, status } : a); };
  return <PageFrame title="Predictive Alerts" subtitle="Early warnings for probable future attack progression">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="Critical" value={`${alerts.filter((a) => a.severity === 'Critical').length}`} tone="risk" /><MetricTile label="High" value={`${alerts.filter((a) => a.severity === 'High').length}`} tone="risk" /><MetricTile label="Forecast Alerts" value={`${alerts.length}`} tone="forecast" /><MetricTile label="Reviewed" value={`${alerts.filter((a) => a.status === 'Reviewed').length}`} tone="observed" /></div>
    <section className="panel mt-4 p-4"><SectionHeader title="Forecast Alert Queue" description="Select an alert to review evidence and analyst-safe actions" action={<div className="flex gap-2"><div className="relative"><Search className="absolute left-2 top-2 size-3 text-muted-foreground" /><Input aria-label="Search alerts" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search alerts" className="h-7 w-40 pl-7 text-[10px]" /></div><Select value={severity} onValueChange={(v) => setSeverity(v as string)}><SelectTrigger size="sm" className="w-28"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="All">All severity</SelectItem><SelectItem value="Critical">Critical</SelectItem><SelectItem value="High">High</SelectItem><SelectItem value="Medium">Medium</SelectItem></SelectContent></Select></div>} />
      {rows.length ? <Table className="text-[9px]"><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Severity</TableHead><TableHead>Source</TableHead><TableHead>Target</TableHead><TableHead>Current Stage</TableHead><TableHead>Predicted Stage</TableHead><TableHead>Probability</TableHead><TableHead>Status</TableHead><TableHead /></TableRow></TableHeader><TableBody>{rows.map((alert) => <TableRow key={alert.id}><TableCell>{alert.time}</TableCell><TableCell><span className={cn('rounded-sm px-1.5 py-1 text-[8px] font-bold', alert.severity === 'Critical' ? 'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300' : alert.severity === 'High' ? 'bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-300' : 'bg-amber-100 text-amber-700')}>{alert.severity}</span></TableCell><TableCell className="font-mono">{alert.source}</TableCell><TableCell>{alert.target}</TableCell><TableCell className="text-emerald-600">{alert.current}</TableCell><TableCell className="text-indigo-600 dark:text-indigo-300">{alert.predicted}</TableCell><TableCell className="font-bold">{alert.probability}%</TableCell><TableCell>{alert.status}</TableCell><TableCell><Button aria-label={`View ${alert.id}`} variant="ghost" size="icon-xs" onClick={() => setSelected(alert)}><Eye /></Button></TableCell></TableRow>)}</TableBody></Table> : <div className="grid h-32 place-items-center text-[10px] text-muted-foreground">No demo alerts match the current filters.</div>}
    </section>
    <Sheet open={Boolean(selected)} onOpenChange={(open) => { if (!open) setSelected(null); }}><SheetContent className="w-full sm:max-w-md"><SheetHeader><div className="flex items-center gap-2 text-indigo-600"><ShieldAlert className="size-4" /><span className="text-[9px] font-bold uppercase tracking-wider">Forecast Alert</span></div><SheetTitle className="mt-2">{selected?.id} · {selected?.predicted}</SheetTitle><SheetDescription>{selected?.description}</SheetDescription></SheetHeader>{selected && <div className="overflow-y-auto px-4"><dl className="space-y-2 text-[9px]">{[['Affected asset', selected.target], ['Source', selected.source], ['Current stage', selected.current], ['Predicted stage', selected.predicted], ['Probability', `${selected.probability}%`], ['Status', selected.status]].map(([label, value]) => <div key={label} className="flex border-b py-2"><dt className="text-muted-foreground">{label}</dt><dd className="ml-auto font-bold">{value}</dd></div>)}</dl><h3 className="mt-5 text-[10px] font-bold">Evidence</h3><ul className="mt-2 space-y-2 text-[9px] text-muted-foreground">{selected.evidence.map((e) => <li key={e} className="flex gap-2"><BellRing className="size-3 text-primary" />{e}</li>)}</ul><h3 className="mt-5 text-[10px] font-bold">Recommended analyst action</h3><p className="mt-2 rounded-md bg-muted p-3 text-[9px] leading-relaxed">{selected.action}</p><p className="mt-3 text-[8px] text-muted-foreground">Advisory only. CyberDrishti does not perform blocking, isolation or firewall changes.</p></div>}<SheetFooter><Button variant="outline" onClick={() => selected && update(selected.id, 'Investigating')}>Investigate</Button><Button variant="outline" render={<Link href="/attack-forecast" />}>View Forecast</Button><Button onClick={() => selected && update(selected.id, 'Reviewed')}>Mark Reviewed</Button></SheetFooter></SheetContent></Sheet>
  </PageFrame>;
}
